// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod shardwire {


#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_BODY: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_BODY: u8 = 4;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_BODY: [Body; 5] = [
  Body::NONE,
  Body::PutShardRequest,
  Body::PutShardResponse,
  Body::GetShardRequest,
  Body::GetShardResponse,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Body(pub u8);
#[allow(non_upper_case_globals)]
impl Body {
  pub const NONE: Self = Self(0);
  pub const PutShardRequest: Self = Self(1);
  pub const PutShardResponse: Self = Self(2);
  pub const GetShardRequest: Self = Self(3);
  pub const GetShardResponse: Self = Self(4);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 4;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::PutShardRequest,
    Self::PutShardResponse,
    Self::GetShardRequest,
    Self::GetShardResponse,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::PutShardRequest => Some("PutShardRequest"),
      Self::PutShardResponse => Some("PutShardResponse"),
      Self::GetShardRequest => Some("GetShardRequest"),
      Self::GetShardResponse => Some("GetShardResponse"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for Body {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for Body {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for Body {
    type Output = Body;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for Body {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for Body {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Body {}
pub struct BodyUnionTableOffset {}

pub enum PutShardRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PutShardRequest<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for PutShardRequest<'a> {
  type Inner = PutShardRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> PutShardRequest<'a> {
  pub const VT_BUCKET: ::flatbuffers::VOffsetT = 4;
  pub const VT_KEY: ::flatbuffers::VOffsetT = 6;
  pub const VT_SHARD_IDX: ::flatbuffers::VOffsetT = 8;
  pub const VT_DATA: ::flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    PutShardRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PutShardRequestArgs<'args>
  ) -> ::flatbuffers::WIPOffset<PutShardRequest<'bldr>> {
    let mut builder = PutShardRequestBuilder::new(_fbb);
    if let Some(x) = args.data { builder.add_data(x); }
    builder.add_shard_idx(args.shard_idx);
    if let Some(x) = args.key { builder.add_key(x); }
    if let Some(x) = args.bucket { builder.add_bucket(x); }
    builder.finish()
  }


  #[inline]
  pub fn bucket(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PutShardRequest::VT_BUCKET, None)}
  }
  #[inline]
  pub fn key(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PutShardRequest::VT_KEY, None)}
  }
  #[inline]
  pub fn shard_idx(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(PutShardRequest::VT_SHARD_IDX, Some(0)).unwrap()}
  }
  #[inline]
  pub fn data(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(PutShardRequest::VT_DATA, None)}
  }
}

impl ::flatbuffers::Verifiable for PutShardRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("bucket", Self::VT_BUCKET, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("key", Self::VT_KEY, false)?
     .visit_field::<u32>("shard_idx", Self::VT_SHARD_IDX, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("data", Self::VT_DATA, false)?
     .finish();
    Ok(())
  }
}
pub struct PutShardRequestArgs<'a> {
    pub bucket: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub key: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub shard_idx: u32,
    pub data: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for PutShardRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    PutShardRequestArgs {
      bucket: None,
      key: None,
      shard_idx: 0,
      data: None,
    }
  }
}

pub struct PutShardRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PutShardRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_bucket(&mut self, bucket: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PutShardRequest::VT_BUCKET, bucket);
  }
  #[inline]
  pub fn add_key(&mut self, key: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PutShardRequest::VT_KEY, key);
  }
  #[inline]
  pub fn add_shard_idx(&mut self, shard_idx: u32) {
    self.fbb_.push_slot::<u32>(PutShardRequest::VT_SHARD_IDX, shard_idx, 0);
  }
  #[inline]
  pub fn add_data(&mut self, data: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PutShardRequest::VT_DATA, data);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PutShardRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PutShardRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<PutShardRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for PutShardRequest<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("PutShardRequest");
      ds.field("bucket", &self.bucket());
      ds.field("key", &self.key());
      ds.field("shard_idx", &self.shard_idx());
      ds.field("data", &self.data());
      ds.finish()
  }
}
pub enum PutShardResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PutShardResponse<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for PutShardResponse<'a> {
  type Inner = PutShardResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> PutShardResponse<'a> {
  pub const VT_OK: ::flatbuffers::VOffsetT = 4;
  pub const VT_ERROR: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    PutShardResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PutShardResponseArgs<'args>
  ) -> ::flatbuffers::WIPOffset<PutShardResponse<'bldr>> {
    let mut builder = PutShardResponseBuilder::new(_fbb);
    if let Some(x) = args.error { builder.add_error(x); }
    builder.add_ok(args.ok);
    builder.finish()
  }


  #[inline]
  pub fn ok(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(PutShardResponse::VT_OK, Some(false)).unwrap()}
  }
  #[inline]
  pub fn error(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PutShardResponse::VT_ERROR, None)}
  }
}

impl ::flatbuffers::Verifiable for PutShardResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<bool>("ok", Self::VT_OK, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("error", Self::VT_ERROR, false)?
     .finish();
    Ok(())
  }
}
pub struct PutShardResponseArgs<'a> {
    pub ok: bool,
    pub error: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for PutShardResponseArgs<'a> {
  #[inline]
  fn default() -> Self {
    PutShardResponseArgs {
      ok: false,
      error: None,
    }
  }
}

pub struct PutShardResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PutShardResponseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_ok(&mut self, ok: bool) {
    self.fbb_.push_slot::<bool>(PutShardResponse::VT_OK, ok, false);
  }
  #[inline]
  pub fn add_error(&mut self, error: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PutShardResponse::VT_ERROR, error);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PutShardResponseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PutShardResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<PutShardResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for PutShardResponse<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("PutShardResponse");
      ds.field("ok", &self.ok());
      ds.field("error", &self.error());
      ds.finish()
  }
}
pub enum GetShardRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct GetShardRequest<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for GetShardRequest<'a> {
  type Inner = GetShardRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> GetShardRequest<'a> {
  pub const VT_BUCKET: ::flatbuffers::VOffsetT = 4;
  pub const VT_KEY: ::flatbuffers::VOffsetT = 6;
  pub const VT_SHARD_IDX: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    GetShardRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args GetShardRequestArgs<'args>
  ) -> ::flatbuffers::WIPOffset<GetShardRequest<'bldr>> {
    let mut builder = GetShardRequestBuilder::new(_fbb);
    builder.add_shard_idx(args.shard_idx);
    if let Some(x) = args.key { builder.add_key(x); }
    if let Some(x) = args.bucket { builder.add_bucket(x); }
    builder.finish()
  }


  #[inline]
  pub fn bucket(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(GetShardRequest::VT_BUCKET, None)}
  }
  #[inline]
  pub fn key(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(GetShardRequest::VT_KEY, None)}
  }
  #[inline]
  pub fn shard_idx(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(GetShardRequest::VT_SHARD_IDX, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for GetShardRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("bucket", Self::VT_BUCKET, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("key", Self::VT_KEY, false)?
     .visit_field::<u32>("shard_idx", Self::VT_SHARD_IDX, false)?
     .finish();
    Ok(())
  }
}
pub struct GetShardRequestArgs<'a> {
    pub bucket: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub key: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub shard_idx: u32,
}
impl<'a> Default for GetShardRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    GetShardRequestArgs {
      bucket: None,
      key: None,
      shard_idx: 0,
    }
  }
}

pub struct GetShardRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> GetShardRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_bucket(&mut self, bucket: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(GetShardRequest::VT_BUCKET, bucket);
  }
  #[inline]
  pub fn add_key(&mut self, key: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(GetShardRequest::VT_KEY, key);
  }
  #[inline]
  pub fn add_shard_idx(&mut self, shard_idx: u32) {
    self.fbb_.push_slot::<u32>(GetShardRequest::VT_SHARD_IDX, shard_idx, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> GetShardRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    GetShardRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<GetShardRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for GetShardRequest<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("GetShardRequest");
      ds.field("bucket", &self.bucket());
      ds.field("key", &self.key());
      ds.field("shard_idx", &self.shard_idx());
      ds.finish()
  }
}
pub enum GetShardResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct GetShardResponse<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for GetShardResponse<'a> {
  type Inner = GetShardResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> GetShardResponse<'a> {
  pub const VT_OK: ::flatbuffers::VOffsetT = 4;
  pub const VT_ERROR: ::flatbuffers::VOffsetT = 6;
  pub const VT_DATA: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    GetShardResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args GetShardResponseArgs<'args>
  ) -> ::flatbuffers::WIPOffset<GetShardResponse<'bldr>> {
    let mut builder = GetShardResponseBuilder::new(_fbb);
    if let Some(x) = args.data { builder.add_data(x); }
    if let Some(x) = args.error { builder.add_error(x); }
    builder.add_ok(args.ok);
    builder.finish()
  }


  #[inline]
  pub fn ok(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(GetShardResponse::VT_OK, Some(false)).unwrap()}
  }
  #[inline]
  pub fn error(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(GetShardResponse::VT_ERROR, None)}
  }
  #[inline]
  pub fn data(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(GetShardResponse::VT_DATA, None)}
  }
}

impl ::flatbuffers::Verifiable for GetShardResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<bool>("ok", Self::VT_OK, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("error", Self::VT_ERROR, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("data", Self::VT_DATA, false)?
     .finish();
    Ok(())
  }
}
pub struct GetShardResponseArgs<'a> {
    pub ok: bool,
    pub error: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub data: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for GetShardResponseArgs<'a> {
  #[inline]
  fn default() -> Self {
    GetShardResponseArgs {
      ok: false,
      error: None,
      data: None,
    }
  }
}

pub struct GetShardResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> GetShardResponseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_ok(&mut self, ok: bool) {
    self.fbb_.push_slot::<bool>(GetShardResponse::VT_OK, ok, false);
  }
  #[inline]
  pub fn add_error(&mut self, error: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(GetShardResponse::VT_ERROR, error);
  }
  #[inline]
  pub fn add_data(&mut self, data: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(GetShardResponse::VT_DATA, data);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> GetShardResponseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    GetShardResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<GetShardResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for GetShardResponse<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("GetShardResponse");
      ds.field("ok", &self.ok());
      ds.field("error", &self.error());
      ds.field("data", &self.data());
      ds.finish()
  }
}
pub enum EnvelopeOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Envelope<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Envelope<'a> {
  type Inner = Envelope<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Envelope<'a> {
  pub const VT_BODY_TYPE: ::flatbuffers::VOffsetT = 4;
  pub const VT_BODY: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Envelope { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args EnvelopeArgs
  ) -> ::flatbuffers::WIPOffset<Envelope<'bldr>> {
    let mut builder = EnvelopeBuilder::new(_fbb);
    if let Some(x) = args.body { builder.add_body(x); }
    builder.add_body_type(args.body_type);
    builder.finish()
  }


  #[inline]
  pub fn body_type(&self) -> Body {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Body>(Envelope::VT_BODY_TYPE, Some(Body::NONE)).unwrap()}
  }
  #[inline]
  pub fn body(&self) -> Option<::flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(Envelope::VT_BODY, None)}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn body_as_put_shard_request(&self) -> Option<PutShardRequest<'a>> {
    if self.body_type() == Body::PutShardRequest {
      self.body().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { PutShardRequest::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn body_as_put_shard_response(&self) -> Option<PutShardResponse<'a>> {
    if self.body_type() == Body::PutShardResponse {
      self.body().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { PutShardResponse::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn body_as_get_shard_request(&self) -> Option<GetShardRequest<'a>> {
    if self.body_type() == Body::GetShardRequest {
      self.body().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { GetShardRequest::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn body_as_get_shard_response(&self) -> Option<GetShardResponse<'a>> {
    if self.body_type() == Body::GetShardResponse {
      self.body().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { GetShardResponse::init_from_table(t) }
     })
    } else {
      None
    }
  }

}

impl ::flatbuffers::Verifiable for Envelope<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_union::<Body, _>("body_type", Self::VT_BODY_TYPE, "body", Self::VT_BODY, false, |key, v, pos| {
        match key {
          Body::PutShardRequest => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<PutShardRequest>>("Body::PutShardRequest", pos),
          Body::PutShardResponse => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<PutShardResponse>>("Body::PutShardResponse", pos),
          Body::GetShardRequest => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<GetShardRequest>>("Body::GetShardRequest", pos),
          Body::GetShardResponse => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<GetShardResponse>>("Body::GetShardResponse", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct EnvelopeArgs {
    pub body_type: Body,
    pub body: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for EnvelopeArgs {
  #[inline]
  fn default() -> Self {
    EnvelopeArgs {
      body_type: Body::NONE,
      body: None,
    }
  }
}

pub struct EnvelopeBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> EnvelopeBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_body_type(&mut self, body_type: Body) {
    self.fbb_.push_slot::<Body>(Envelope::VT_BODY_TYPE, body_type, Body::NONE);
  }
  #[inline]
  pub fn add_body(&mut self, body: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Envelope::VT_BODY, body);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> EnvelopeBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    EnvelopeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Envelope<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Envelope<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Envelope");
      ds.field("body_type", &self.body_type());
      match self.body_type() {
        Body::PutShardRequest => {
          if let Some(x) = self.body_as_put_shard_request() {
            ds.field("body", &x)
          } else {
            ds.field("body", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Body::PutShardResponse => {
          if let Some(x) = self.body_as_put_shard_response() {
            ds.field("body", &x)
          } else {
            ds.field("body", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Body::GetShardRequest => {
          if let Some(x) = self.body_as_get_shard_request() {
            ds.field("body", &x)
          } else {
            ds.field("body", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Body::GetShardResponse => {
          if let Some(x) = self.body_as_get_shard_response() {
            ds.field("body", &x)
          } else {
            ds.field("body", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("body", &x)
        },
      };
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Envelope`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_envelope_unchecked`.
pub fn root_as_envelope(buf: &[u8]) -> Result<Envelope<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<Envelope>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Envelope` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_envelope_unchecked`.
pub fn size_prefixed_root_as_envelope(buf: &[u8]) -> Result<Envelope<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<Envelope>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Envelope` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_envelope_unchecked`.
pub fn root_as_envelope_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Envelope<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<Envelope<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Envelope` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_envelope_unchecked`.
pub fn size_prefixed_root_as_envelope_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Envelope<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<Envelope<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Envelope and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Envelope`.
pub unsafe fn root_as_envelope_unchecked(buf: &[u8]) -> Envelope<'_> {
  unsafe { ::flatbuffers::root_unchecked::<Envelope>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Envelope and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Envelope`.
pub unsafe fn size_prefixed_root_as_envelope_unchecked(buf: &[u8]) -> Envelope<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Envelope>(buf) }
}
#[inline]
pub fn finish_envelope_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<Envelope<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_envelope_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<Envelope<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod shardwire

