
name: testcase-workflow

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  # Python client tests
  client-tests:
    name: Client tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flatbuffers pytest requests flake8
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Init submodules
      run: git submodule update --init --recursive
      
    - name: Test with pytest
      working-directory: client/python-sdk
      run: |
        pytest ciaos/test.py

  # Rust server tests
  server-tests:
    name: Server tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Build server
      working-directory: server
      run: cargo build
    - name: Run server tests
      working-directory: server
      run: cargo test
